#Global
app:
  client:
    geography:
      srid: 4326
  datasource:
    osm:
      url: jdbc:postgresql://185.124.188.247:5432/model
      username: model
      password: Bc9Q_13k$h![lJx7oW1vc
      srid: 3857
    fires:
      url: jdbc:postgresql://localhost:5432/fires
      username: nikitorches
      password: admin
      srid: 4326

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
#Resources
  main:
    banner-mode: off
  resources:
    add-mappings: true
