#Global
app:
  epsg:
    web-mercator: 3857
    wgs-84: 4326

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twinkle_db
    username: twinkle_user
    password: twinkle_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  #Resources
  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true